### ISSUE TITLE
Question about order of operations: nar_audio_prenet and nar_audio_position

### ISSUE THREAD

**Issue by Misha24-10** [lifeiteng/valle#180]
I am working with the code in the following snippet (https://github.com/lifeiteng/vall-e/blob/9c69096d603ce13174fb5cb025f185e2e9b36ac7/valle/models/valle.py#L1193C1-L1194C53)
```
y_pos = self.nar_audio_position(y_emb)
y_pos = self.nar_audio_prenet(y_pos)
```
I am uncertain about the order of operations here. Should nar_audio_prenet be applied before nar_audio_position in this context?

**Comment by lifeiteng** [comment]
You can try different order, but the recommended configuration here is `nn.Identity()`
```
self.nar_audio_prenet = nn.Identity()
```
