### ISSUE TITLE
 To avoid abuse, Well-trained models and services will not be provided.

### ISSUE THREAD

**Issue by xalteropsx** [lifeiteng/valle#187]
Broader impacts

Since VALL-E could synthesize speech that maintains speaker identity, it may carry potential risks in misuse of the model, such as spoofing voice identification or impersonating a specific speaker.

To avoid abuse, Well-trained models and services will not be provided.

can u change this policy or i will create it from scratch 

it just make whole thing worse in quality in terms

**Comment by ScottishFold007** [comment]
> Broader impacts
> 
> Since VALL-E could synthesize speech that maintains speaker identity, it may carry potential risks in misuse of the model, such as spoofing voice identification or impersonating a specific speaker.
> 
> To avoid abuse, Well-trained models and services will not be provided.
> 
> can u change this policy or i will create it from scratch
> 
> it just make whole thing worse in quality in terms

Might not have trained for better results and not released to be able to circumvent the situation?
