### ISSUE TITLE
After eight hours of training, the model can synthesize natural speech!

### ISSUE THREAD

**Issue by lifeiteng** [lifeiteng/valle#53]
code branch `position` PR https://github.com/lifeiteng/vall-e/pull/46
egs `https://github.com/lifeiteng/vall-e/tree/position/egs/ljspeech`

synthesised speech https://github.com/lifeiteng/vall-e/tree/position/egs/ljspeech/demos

The next step is to verify `in-context learning capabilities` of VALL-E on a large dataset.

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
Thanks for your work!
Btw current vall-e repo supports prosody transfer feature?
In official demo I can see "Speaker’s Emotion Maintenance".
Looking forward to your reply.
Best Regards!
Petar

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
I have trained model with the latest position branch and finally have got epoch-100.pt file (162MB).
But the results are different from the result yous shared.
My result -> 0.wav: https://drive.google.com/file/d/1HBeubaOxPClPbR7HntxA4708raXZt5eY/view?usp=share_link
                     1.wav: https://drive.google.com/file/d/1HtQRdJRz4yWm-MikyBngpjNB6CUcXgba/view?usp=share_link
Please try to check and let me know about the solutions.
Thanks very much.
Petar

**Comment by primepake** [comment]
how many gpus you trained with?

**Comment by fullstack-dev0727** [comment]
> 

I used one GPU (Tesla V100 GPU).

**Comment by fullstack-dev0727** [comment]
Hi, @lifeiteng 
When we train with LJSpeech dataset, we need to keep all .wav files in /wavs folder.
If we use another data instead of LJSpeech dataset, we can not keep all files in several folders?
Looking forward to your reply.
Best Regards!
Petar

**Comment by divineSix** [comment]
@lifeiteng , I've been unable to reproduce good quality results. For training, I've used the exact same arguments as mentioned in the `egs/ljspeech/README.md`, with the addition of the `world-size` argument for training it on multiple GPUs. 

I'm also using the provided arguments for inference as well, using the 99th epoch checkpoint instead of the 100th. The audio files that are generated are very garbled and have unintelligible speech. 

##### Training Arguments
```
python3 bin/trainer.py --max-duration 72 --filter-max-duration 14 --num-buckets 6 --dtype "float32" --save-every-n 10000 --model-name valle --norm-first true --add-prenet false --decoder-dim 256 --nhead 8 --num-decoder-layers 6 --prefix-mode 0 --base-lr 0.05 --warmup-steps 200 --num-epochs 100 --start-epoch 1 --start-batch 0 --accumulate-grad-steps 1 --exp-dir /ssd_scratch/cvit/skosgi242/valle_ckpts/ljspeech --world-size 4
```

##### Inference Arguments
```
python3 bin/infer.py --output-dir demos --top-k -1 --temperature 1.0 --model-name valle --norm-first true --add-prenet false --decoder-dim 256 --nhead 8 --num-decoder-layers 6 --prefix-mode 0 --text-prompts "In addition, the proposed legislation will insure." --audio-prompts /ssd_scratch/cvit/skosgi242/24K_samples/en_ljspeech_LJ049_0124.wav --text "To get up and running quickly just follow the steps below.|During the period the Commission was giving thought to this situation." --checkpoint /ssd_scratch/cvit/skosgi242/valle_ckpts/ljspeech/epoch-99.pt
```

The [drive link](https://drive.google.com/drive/folders/1Ruid9uDEAkOJUcriBqAFP_oa-NcCFL10?usp=sharing) contains the following information:
- Generated samples
- The checkpoint used
- The training log. 

Please help me figure out where it went wrong. Let me know if you require further information on this.

**Comment by kin0303** [comment]
> Hi, @lifeiteng When we train with LJSpeech dataset, we need to keep all .wav files in /wavs folder. If we use another data instead of LJSpeech dataset, we can not keep all files in several folders? Looking forward to your reply. Best Regards! Petar

Hi, have you got the answer?

**Comment by spacewalkingninja** [comment]
Hey, can anybody pls release their **_BEST_** model please? I need a free model for this pls, got no money to spend on GPUs, need to make a good ai thing to make me money to have to spend on GPUs

**Comment by ksasso1028** [comment]
> > 
> 
> I used one GPU (Tesla V100 GPU).

so 8 hours of training on a single GPU?
